[graph]
all-features = true

[advisories]
unmaintained = "workspace"
yanked = "deny"

[licenses]
allow = ["MIT", "Apache-2.0"]

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
